name: terraform-apply-main

on:
  push:
    branches: ["main"]

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-3
      TF_IN_AUTOMATION: "true"
      GIT_TERMINAL_PROMPT: "0"

    steps:
      - name: Checkout repo public
        uses: actions/checkout@v4

      - name: Configure git auth for private modules (HTTPS)
        shell: bash
        run: |
          git config --global url."https://${{ secrets.MODULES_GH_TOKEN }}:@github.com/".insteadOf "https://github.com/"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform init
        working-directory: modulo-weekly-exercise
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: modulo-weekly-exercise
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform apply -input=false -auto-approve
